In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [17]:
x=np.arange(10).reshape(-1,1)
y=([0,1,0,1,0,1,0,0,1,1])

In [43]:
print(x, y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] [0, 1, 0, 1, 0, 1, 0, 0, 1, 1]


In [19]:
log=LogisticRegression(solver='liblinear', C=10.0, random_state=0)
log.fit(x,y)

LogisticRegression(C=10.0, random_state=0, solver='liblinear')

In [20]:
log.intercept_

array([-0.68524789])

In [21]:
log.coef_

array([[0.15868212]])

In [22]:
# Probability og giving 0 vs 1 [0, 1]
p_pred=log.predict_proba(x)
p_pred

array([[0.66490896, 0.33509104],
       [0.62868178, 0.37131822],
       [0.59094749, 0.40905251],
       [0.55211047, 0.44788953],
       [0.51262716, 0.48737284],
       [0.47298565, 0.52701435],
       [0.43368184, 0.56631816],
       [0.39519495, 0.60480505],
       [0.35796466, 0.64203534],
       [0.32237224, 0.67762776]])

In [23]:
y_pred=log.predict(x)
y_pred

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [24]:
score=log.score(x, y)
score

0.6

In [28]:
conf_mat=confusion_matrix(y, y_pred)
conf_mat

# TP-> 3  FP-> 2
# FN-> 2  TN-> 3

array([[3, 2],
       [2, 3]], dtype=int64)

In [40]:
report=classification_report(y, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.60      0.60      0.60         5
           1       0.60      0.60      0.60         5

    accuracy                           0.60        10
   macro avg       0.60      0.60      0.60        10
weighted avg       0.60      0.60      0.60        10



# Using dataset

In [6]:
from sklearn.datasets import load_breast_cancer
import pandas as pd

In [14]:
df=load_breast_cancer()

In [15]:
x=pd.DataFrame(df['data'], columns=df['feature_names'])

In [16]:
x.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [10]:
# Dependent features
y=pd.DataFrame(data['target'], columns=["target"])
y

target
0         0
1         0
2         0
3         0
4         0
..      ...
564       0
565       0
566       0
567       0
568       1

[569 rows x 1 columns]

In [11]:
# To check the balanced or not
y['target'].value_counts()

target
1    357
0    212
Name: count, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [17]:
x_train, x_test, y_train, y_test=train_test_split(x, y, 
                                                  test_size=0.33, random_state=42)

In [18]:
log=LogisticRegression(solver='liblinear', C=10.0, random_state=0)
log.fit(x_train, y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=10.0, random_state=0, solver='liblinear')

In [19]:
log.intercept_

array([0.9679875])

In [20]:
log.coef_

array([[ 4.92996853,  0.43161787, -0.50142452, -0.01841706, -0.38063179,
        -0.86166194, -1.58028969, -0.99422833, -0.63592606, -0.06187521,
        -0.3762955 ,  3.95368557,  0.22591993, -0.18502761, -0.05556635,
         0.05055563, -0.00801782, -0.10830183, -0.15225145,  0.01298489,
         0.41943828, -0.77115516,  0.05909379, -0.01241642, -0.78781627,
        -2.21935556, -3.38064395, -1.6411533 , -2.34326701, -0.21902675]])

In [22]:
p_pred=log.predict_proba(x_test)
p_pred

array([[1.74585092e-01, 8.25414908e-01],
       [9.99999996e-01, 4.29369279e-09],
       [9.98996650e-01, 1.00335012e-03],
       [5.19770082e-04, 9.99480230e-01],
       [8.95286049e-05, 9.99910471e-01],
       [1.00000000e+00, 4.70516120e-12],
       [1.00000000e+00, 3.14199667e-14],
       [9.94922535e-01, 5.07746479e-03],
       [9.14149635e-03, 9.90858504e-01],
       [3.78221476e-03, 9.96217785e-01],
       [6.71511803e-02, 9.32848820e-01],
       [9.99686825e-01, 3.13174529e-04],
       [3.48920620e-03, 9.96510794e-01],
       [9.73577488e-01, 2.64225120e-02],
       [2.60583194e-03, 9.97394168e-01],
       [9.98581640e-01, 1.41835979e-03],
       [7.69949701e-04, 9.99230050e-01],
       [5.86828444e-06, 9.99994132e-01],
       [1.86574010e-04, 9.99813426e-01],
       [9.99999998e-01, 1.94244383e-09],
       [8.67909221e-02, 9.13209078e-01],
       [4.22931151e-03, 9.95770688e-01],
       [1.00000000e+00, 1.82030450e-11],
       [1.78008629e-03, 9.98219914e-01],
       [2.843302

In [23]:
y_pred=log.predict(x_test)
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1])

In [24]:
score=log.score(x_test, y_test)
score

0.9574468085106383

In [31]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [28]:
conf_mat=confusion_matrix(y_test, y_pred)
conf_mat

array([[ 64,   3],
       [  5, 116]], dtype=int64)

In [30]:
report=classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.93      0.96      0.94        67
           1       0.97      0.96      0.97       121

    accuracy                           0.96       188
   macro avg       0.95      0.96      0.95       188
weighted avg       0.96      0.96      0.96       188



In [32]:
acc_score=accuracy_score(y_test, y_pred)
acc_score

0.9574468085106383